//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace QUẢN_LÝ_KHÁCH_SẠN.Module.BusinessObjects.ORMDataModel1
{

    public partial class BAOCAO : XPObject
    {
        string fMABC;
        public string MABC
        {
            get { return fMABC; }
            set { SetPropertyValue<string>(nameof(MABC), ref fMABC, value); }
        }
        string fTENBC;
        public string TENBC
        {
            get { return fTENBC; }
            set { SetPropertyValue<string>(nameof(TENBC), ref fTENBC, value); }
        }
        string fTTPHONG;
        public string TTPHONG
        {
            get { return fTTPHONG; }
            set { SetPropertyValue<string>(nameof(TTPHONG), ref fTTPHONG, value); }
        }
        string fSLKHACH;
        public string SLKHACH
        {
            get { return fSLKHACH; }
            set { SetPropertyValue<string>(nameof(SLKHACH), ref fSLKHACH, value); }
        }
        string fDOANHTHU;
        public string DOANHTHU
        {
            get { return fDOANHTHU; }
            set { SetPropertyValue<string>(nameof(DOANHTHU), ref fDOANHTHU, value); }
        }
        [Association(@"NHANVIENReferencesBAOCAO"), Aggregated]
        public XPCollection<NHANVIEN> NHANVIENs { get { return GetCollection<NHANVIEN>(nameof(NHANVIENs)); }
        }
        }
}
