//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace QUẢN_LÝ_KHÁCH_SẠN.Module.BusinessObjects.ORMDataModel1
{

    public partial class BOPHAN : XPObject
    {
        string fTENBP;
        public string TENBP
        {
            get { return fTENBP; }
            set { SetPropertyValue<string>(nameof(TENBP), ref fTENBP, value); }
        }
        string fCHUCVU;
        public string CHUCVU
        {
            get { return fCHUCVU; }
            set { SetPropertyValue<string>(nameof(CHUCVU), ref fCHUCVU, value); }
        }
        [Association(@"NHANVIENReferencesBOPHAN"), Aggregated]
        public XPCollection<NHANVIEN> NHANVIENs { get { return GetCollection<NHANVIEN>(nameof(NHANVIENs)); } }
    }

}
