//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace QUẢN_LÝ_KHÁCH_SẠN.Module.BusinessObjects.ORMDataModel1
{

    public partial class CHITIETHOADON : XPObject
    {
        string fMACTHD;
        public string MACTHD
        {
            get { return fMACTHD; }
            set { SetPropertyValue<string>(nameof(MACTHD), ref fMACTHD, value); }
        }
        HOADON fMAHD;
        [Association(@"CHITIETHOADONReferencesHOADON")]
        public HOADON MAHD
        {
            get { return fMAHD; }
            set { SetPropertyValue<HOADON>(nameof(MAHD), ref fMAHD, value); }
        }
        string fTHANHTIEN;
        public string THANHTIEN
        {
            get { return fTHANHTIEN; }
            set { SetPropertyValue<string>(nameof(THANHTIEN), ref fTHANHTIEN, value); }
        }
        decimal fSOGIO;
        public decimal SOGIO
        {
            get { return fSOGIO; }
            set { SetPropertyValue<decimal>(nameof(SOGIO), ref fSOGIO, value); }
        }
        decimal fDONGIA;
        public decimal DONGIA
        {
            get { return fDONGIA; }
            set { SetPropertyValue<decimal>(nameof(DONGIA), ref fDONGIA, value); }
        }
        public decimal Thanhtien
        {
            get
            {
                return (decimal) SOGIO * DONGIA;
            }
        }
    }

}
