//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace QUẢN_LÝ_KHÁCH_SẠN.Module.BusinessObjects.ORMDataModel1
{

    public partial class CHITIETPHIEUTHUE : XPObject
    {
        string fMACTPT;
        public string MACTPT
        {
            get { return fMACTPT; }
            set { SetPropertyValue<string>(nameof(MACTPT), ref fMACTPT, value); }
        }
        string fTENKH;
        public string TENKH
        {
            get { return fTENKH; }
            set { SetPropertyValue<string>(nameof(TENKH), ref fTENKH, value); }
        }
        string fCMND;
        public string CMND
        {
            get { return fCMND; }
            set { SetPropertyValue<string>(nameof(CMND), ref fCMND, value); }
        }
        string fDIACHI;
        public string DIACHI
        {
            get { return fDIACHI; }
            set { SetPropertyValue<string>(nameof(DIACHI), ref fDIACHI, value); }
        }
        PHIEUTHUE fMAPT;
        [Association(@"CHITIETPHIEUTHUEReferencesPHIEUTHUE")]
        public PHIEUTHUE MAPT
        {
            get { return fMAPT; }
            set { SetPropertyValue<PHIEUTHUE>(nameof(MAPT), ref fMAPT, value); }
        }
    }

}
