//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace QUẢN_LÝ_KHÁCH_SẠN.Module.BusinessObjects.ORMDataModel1
{

    public partial class DATDICHVU : XPObject
    {
        string fMADDV;
        public string MADDV
        {
            get { return fMADDV; }
            set { SetPropertyValue<string>(nameof(MADDV), ref fMADDV, value); }
        }
        DICHVU fMADV;
        [Association(@"DATDICHVUReferencesDICHVU")]
        public DICHVU MADV
        {
            get { return fMADV; }
            set { SetPropertyValue<DICHVU>(nameof(MADV), ref fMADV, value); }
        }
        string fMAP;
        public string MAP
        {
            get { return fMAP; }
            set { SetPropertyValue<string>(nameof(MAP), ref fMAP, value); }
        }
        string fSOLAN;
        public string SOLAN
        {
            get { return fSOLAN; }
            set { SetPropertyValue<string>(nameof(SOLAN), ref fSOLAN, value); }
        }
    }

}
