//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace QUẢN_LÝ_KHÁCH_SẠN.Module.BusinessObjects.ORMDataModel1
{

    public partial class DICHVU : XPObject
    {
        string fMADV;
        public string MADV
        {
            get { return fMADV; }
            set { SetPropertyValue<string>(nameof(MADV), ref fMADV, value); }
        }
        string fTENDV;
        public string TENDV
        {
            get { return fTENDV; }
            set { SetPropertyValue<string>(nameof(TENDV), ref fTENDV, value); }
        }
        string fMOTA;
        public string MOTA
        {
            get { return fMOTA; }
            set { SetPropertyValue<string>(nameof(MOTA), ref fMOTA, value); }
        }
        string fGIA;
        public string GIA
        {
            get { return fGIA; }
            set { SetPropertyValue<string>(nameof(GIA), ref fGIA, value); }
        }
        [Association(@"DATDICHVUReferencesDICHVU"), Aggregated]
        public XPCollection<DATDICHVU> DATDICHVUs { get { return GetCollection<DATDICHVU>(nameof(DATDICHVUs)); } }
    }

}
