//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace QUẢN_LÝ_KHÁCH_SẠN.Module.BusinessObjects.ORMDataModel1
{

    public partial class HOADON : XPObject
    {
        string fMAHD;
        public string MAHD
        {
            get { return fMAHD; }
            set { SetPropertyValue<string>(nameof(MAHD), ref fMAHD, value); }
        }
        DATPHONG fMADP;
        [Association(@"HOADONReferencesDATPHONG")]
        public DATPHONG MADP
        {
            get { return fMADP; }
            set { SetPropertyValue<DATPHONG>(nameof(MADP), ref fMADP, value); }
        }
       
        public decimal TONGTIEN
        {
            get
            {
                decimal tien = 0;
                foreach(CHITIETHOADON item in CHITIETHOADONs)
                {
                    tien += item.Thanhtien;
                }
                return tien;
            }

        }
        [Association(@"CHITIETHOADONReferencesHOADON"), Aggregated]
        public XPCollection<CHITIETHOADON> CHITIETHOADONs { get { return GetCollection<CHITIETHOADON>(nameof(CHITIETHOADONs)); } }
    }

}
