//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace QUẢN_LÝ_KHÁCH_SẠN.Module.BusinessObjects.ORMDataModel1
{

    public partial class LOAIPHONG : XPObject
    {
        string fMALP;
        public string MALP
        {
            get { return fMALP; }
            set { SetPropertyValue<string>(nameof(MALP), ref fMALP, value); }
        }
        string fTENP;
        public string TENP
        {
            get { return fTENP; }
            set { SetPropertyValue<string>(nameof(TENP), ref fTENP, value); }
        }
        string fMOTA;
        public string MOTA
        {
            get { return fMOTA; }
            set { SetPropertyValue<string>(nameof(MOTA), ref fMOTA, value); }
        }
        [Association(@"PHONGReferencesLOAIPHONG"), Aggregated]
        public XPCollection<PHONG> PHONGs { get { return GetCollection<PHONG>(nameof(PHONGs)); } }
    }

}
