//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace QUẢN_LÝ_KHÁCH_SẠN.Module.BusinessObjects.ORMDataModel1
{

    public partial class NHANVIEN : XPObject
    {
        string fMANV;
        public string MANV
        {
            get { return fMANV; }
            set { SetPropertyValue<string>(nameof(MANV), ref fMANV, value); }
        }
        string fHOTEN;
        public string HOTEN
        {
            get { return fHOTEN; }
            set { SetPropertyValue<string>(nameof(HOTEN), ref fHOTEN, value); }
        }
        BOPHAN fPHONG;
        [Association(@"NHANVIENReferencesBOPHAN")]
        public BOPHAN PHONG
        {
            get { return fPHONG; }
            set { SetPropertyValue<BOPHAN>(nameof(PHONG), ref fPHONG, value); }
        }
        string fSDT;
        public string SDT
        {
            get { return fSDT; }
            set { SetPropertyValue<string>(nameof(SDT), ref fSDT, value); }
        }
        string fDIACHI;
        public string DIACHI
        {
            get { return fDIACHI; }
            set { SetPropertyValue<string>(nameof(DIACHI), ref fDIACHI, value); }
        }
        TAIKHOAN fMATK;
        [Association(@"NHANVIENReferencesTAIKHOAN")]
        public TAIKHOAN MATK
        {
            get { return fMATK; }
            set { SetPropertyValue<TAIKHOAN>(nameof(MATK), ref fMATK, value); }
        }
        BAOCAO fMABC;
        [Association(@"NHANVIENReferencesBAOCAO")]
        public BAOCAO MABC
        {
            get { return fMABC; }
            set { SetPropertyValue<BAOCAO>(nameof(MABC), ref fMABC, value); }
        }
        [Association(@"DATPHONGReferencesNHANVIEN"), Aggregated]
        public XPCollection<DATPHONG> DATPHONGs { get { return GetCollection<DATPHONG>(nameof(DATPHONGs)); } }
    }

}
