//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace QUẢN_LÝ_KHÁCH_SẠN.Module.BusinessObjects.ORMDataModel1
{

    public partial class PHIEUTHUE : XPObject
    {
        string fMAPT;
        public string MAPT
        {
            get { return fMAPT; }
            set { SetPropertyValue<string>(nameof(MAPT), ref fMAPT, value); }
        }
        string fNGAYTHUE;
        public string NGAYTHUE
        {
            get { return fNGAYTHUE; }
            set { SetPropertyValue<string>(nameof(NGAYTHUE), ref fNGAYTHUE, value); }
        }
        PHONG fMAP;
        [Association(@"PHIEUTHUEReferencesPHONG")]
        public PHONG MAP
        {
            get { return fMAP; }
            set { SetPropertyValue<PHONG>(nameof(MAP), ref fMAP, value); }
        }
        KHACHHANG fMAKH;
        [Association(@"PHIEUTHUEReferencesKHACHHANG")]
        public KHACHHANG MAKH
        {
            get { return fMAKH; }
            set { SetPropertyValue<KHACHHANG>(nameof(MAKH), ref fMAKH, value); }
        }
        [Association(@"CHITIETPHIEUTHUEReferencesPHIEUTHUE"), Aggregated]
        public XPCollection<CHITIETPHIEUTHUE> CHITIETPHIEUTHUEs { get { return GetCollection<CHITIETPHIEUTHUE>(nameof(CHITIETPHIEUTHUEs)); } }
    }

}
