//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace QUẢN_LÝ_KHÁCH_SẠN.Module.BusinessObjects.ORMDataModel1
{

    public partial class PHONG : XPObject
    {
        string fMAP;
        public string MAP
        {
            get { return fMAP; }
            set { SetPropertyValue<string>(nameof(MAP), ref fMAP, value); }
        }
        LOAIPHONG fMALP;
        [Association(@"PHONGReferencesLOAIPHONG")]
        public LOAIPHONG MALP
        {
            get { return fMALP; }
            set { SetPropertyValue<LOAIPHONG>(nameof(MALP), ref fMALP, value); }
        }
        string fTRANGTHAI;
        public string TRANGTHAI
        {
            get { return fTRANGTHAI; }
            set { SetPropertyValue<string>(nameof(TRANGTHAI), ref fTRANGTHAI, value); }
        }
        [Association(@"DATPHONGReferencesPHONG"), Aggregated]
        public XPCollection<DATPHONG> DATPHONGs { get { return GetCollection<DATPHONG>(nameof(DATPHONGs)); } }
        [Association(@"PHIEUTHUEReferencesPHONG"), Aggregated]
        public XPCollection<PHIEUTHUE> PHIEUTHUEs { get { return GetCollection<PHIEUTHUE>(nameof(PHIEUTHUEs)); } }
    }

}
